#pragma once
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <stdlib.h>
#include <string>
#include <algorithm>
#include <vector>
#include <limits>
#include <ctime>
#include <cstdlib>
#include <cctype>
#include <vector>

using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::fixed;
using std::string;
using std::copy;
using std::vector;
using std::numeric_limits;
using std::sort;
using std::toupper;